services:
  catalogue:
    build:
      context: .
      dockerfile: catalogue.Dockerfile
    image: bhukyadevops/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build:
      context: .
      dockerfile: user.Dockerfile
    image: bhukyadevops/user:1.0.0
    container_name: user
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: bhukyadevops/frontend:1.0.0
    container_name: frontend
    depends_on:
      - catalogue
      - user

  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    image: bhukyadevops/mongodb:1.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: false
